runtime: nodejs14

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: nuxt-dist/dist/client
    secure: never

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: never

  - url: /.*
    script: auto
    secure: never

env_variables:
  HOST: '0.0.0.0'